# Bài tập tuần 2 (Deadline: 18/07/2021)
## Bài tập số 1:

In [7]:
# Definition of survey_vector
survey_vector <- c("R", "R", "L", "L", "R", "R", "C", "C")

# Create survey_vector as a factor: survey_factor
survey_factor = factor(survey_vector)

# Print survey_factor
print(survey_factor)

# Print levels of survey_factor
print(levels(survey_factor))

# Print nlevels of survey_factor
print(nlevels(survey_factor))

# How many elements of each factor?
table(survey_factor)

[1] R R L L R R C C
Levels: C L R
[1] "C" "L" "R"
[1] 3


survey_factor
C L R 
2 2 4 

## Bài tập số 2:


In [12]:
my_vector = c(1:10)
my_vector

[1]  1  2  3  4  5  6  7  8  9 10

In [23]:
# Create my_vector: 1 up to 10
my_vector = c(1:10)

# Create my_matrix (3x3): 1 up to 9
my_matrix = matrix(c(1:9), nrow=3)

# Create my_factor from sizes
sizes <-c("M","S","L","L","M")
my_factor = factor(sizes)

# Construct my_list with the three data structures above
my_list = list(my_vector, my_matrix, my_factor)

# Construct my_super_list with the four data structures above
my_super_list = list(my_vector, my_matrix, my_factor, my_list)

# Display structure of my_super_list (Use str())
str(my_super_list)

# Print my_matrix, sum of my_matrix
print(my_matrix)
print(sum(my_matrix))

# Sum of even elements in my_matrix
sum = 0
for (x in my_matrix) {
    if (x%%2 == 0) {
        sum = sum + x
    }
}
print(sum)

List of 4
 $ : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
 $ : Factor w/ 3 levels "L","M","S": 2 3 1 1 2
 $ :List of 3
  ..$ : int [1:10] 1 2 3 4 5 6 7 8 9 10
  ..$ : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
  ..$ : Factor w/ 3 levels "L","M","S": 2 3 1 1 2
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] 45
[1] 20


## Bài tập số 3:


In [105]:
# Create my_matrix (4x4): each element is a randomly generated prime number.
# First create funtion check_prime
check_prime = function(x) {
    ifelse((x %in% c(1,2)), TRUE, ifelse(all(x %% (2:(x - 1)) != 0), TRUE, FALSE))
}

# Second create a list 1000 number, then filter prime
number = c(1:1000)
prime_number = number[sapply(number, check_prime)]

# Sample random 16 number, than tranform to matrix
prime_sample = sample(prime_number, 16)
my_matrix = matrix(prime_sample, nrow=4)
my_matrix

[,1] [,2] [,3] [,4]
[1,] 499  593  199  293 
[2,] 523  281   23  389 
[3,]   5  103  647  787 
[4,] 127  859  929   41

In [108]:
# Sum the elements on the main diagonal of the matrix
sum_diagonal = function(my_matrix) {
    sum = 0
    for (i in (1:nrow(my_matrix))) {
        for (j in (1:ncol(my_matrix))) {
            if(i == j) {
                sum = sum + my_matrix[i, j]
            }
        }
    }
    return (sum)
}
print(sum_diagonal(my_matrix))

[1] 1468


In [117]:
# (Note: Build function to create_matrix, function to test_Prime number, and function to Sum... >> Call fucntion)
build_prime_matrix = function(n_rows, n_cols) {    
    # Main work
    number = c(1:1000)
    prime_number = number[sapply(number, check_prime)]
    prime_sample = sample(prime_number, n_rows * n_cols)
    my_matrix = matrix(prime_sample, nrow=n_rows)
    return (my_matrix)
}

my_matrix = build_prime_matrix(4, 4)

In [118]:
sum = sum_diagonal(my_matrix)
print(paste('Random prime matrix:'))
prmatrix(my_matrix)
print(paste('Diagonal sum of prime matrix is:', sum))

[1] "Random prime matrix:"
     [,1] [,2] [,3] [,4]
[1,]  463  521  409  547
[2,]  181  199  863  251
[3,]  607  643  811  787
[4,]  211  569  281  887
[1] "Diagonal sum of prime matrix is: 2360"


## Bài tập số 4:

In [135]:
# Create my_array (4, 4, 2): from 2 matrices created by calling function create_matrix (Bai tap so 3)
mx_1 = build_prime_matrix(4, 4)
mx_2 = build_prime_matrix(4, 4)
my_array = array(c(mx_1, mx_2), dim = c(4, 4, 2))
print(my_array)

, , 1

     [,1] [,2] [,3] [,4]
[1,]  509  227  857   31
[2,]  587   67   61  383
[3,]  541  353  179  937
[4,]  503  733   23  743

, , 2

     [,1] [,2] [,3] [,4]
[1,]  179   79  983    1
[2,]  103  173  107  149
[3,]  331  613  167  577
[4,]  419  229  191  239



In [167]:
row_min_func = function(mx) {
    apply(mx, 1, 'min')
}

col_max_func = function(mx) {
    apply(mx, 2, 'max')
}

In [166]:
# Use apply to calculate the min of the rows across all the matrices.
apply(my_array, 3, row_min_func)

# Use apply to calculate the max of the columns across all the matrices.
apply(my_array, 3, col_max_func)

# Use apply to calculate the sum of each matrix in my_array
apply(my_array, 3, 'sum')

[,1] [,2]
[1,]  31    1 
[2,]  61  103 
[3,] 179  167 
[4,]  23  191

[,1] [,2]
[1,] 587  419 
[2,] 733  613 
[3,] 857  983 
[4,] 937  577

[1] 6734 4540

## Bài tập số 5

In [204]:
# Create title, actors, reviews
title = "The Shining"
actors_vector <- c("Jack Nicholson","Shelley Duvall","Danny Lloyd","Scatman Crothers","Barry Nelson")
reviews_factor <- factor(c("Good", "OK", "Good", "Perfect", "Bad", "Perfect", "Good"), 
                  ordered = TRUE, levels = c("Bad", "OK", "Good", "Perfect"))

# Create the list 'shining_list' from 3 vectors above
shining_list = list(title = title, actors_vector = actors_vector, reviews_factor=reviews_factor)

# Select the last actor from list: last_actor
last_actor = shining_list$actors_vector[length(actors_vector)]
print(last_actor)

# Select the second review from list: second_review
second_review = shining_list$reviews_factor[2]
print(second_review)

# Add the element 'release_year' = 1980 to shining_list
shining_list['release_year'] = 1980

# Add the element 'director' = "Stanley Kubrick" to shining_list
shining_list['director'] = 'Stanley Kubrick'

# Print list shining_list
print(shining_list)

# Print the structure of shining_list
str(shining_list)

[1] "Barry Nelson"
[1] OK
Levels: Bad < OK < Good < Perfect
$title
[1] "The Shining"

$actors_vector
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

$reviews_factor
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect

$release_year
[1] 1980

$director
[1] "Stanley Kubrick"

List of 5
 $ title         : chr "The Shining"
 $ actors_vector : chr [1:5] "Jack Nicholson" "Shelley Duvall" "Danny Lloyd" "Scatman Crothers" ...
 $ reviews_factor: Ord.factor w/ 4 levels "Bad"<"OK"<"Good"<..: 3 2 3 4 1 4 3
 $ release_year  : num 1980
 $ director      : chr "Stanley Kubrick"


## Bài tập số 6: Hãy thực hiện những yêu cầu sau với R-core dataframe và/ hoặc Tidyverse
1. Cho dữ liệu mtcars cho sẵn trong R datasets. Đọc dữ liệu. Hiển thị thông tin một số dòng đầu của dữ liệu. In thông tin thống kê chung.
2. Tạo sub_data chỉ có các thông tin mpg, hp, wt, gear
3. Tạp cột mới km_per_litre trong sub_data theo công thức: 1 mpg = 0.425 km/l
4. Tạo sub_data_unique lấy từ mtcars nhưng loại bỏ các dòng trùng (dùng distinct()
5. In sub_data_unique với giá trị được sắp xếp giảm dần theo mpg, tăng dần theo hp
6. Lọc các xe mà trong tên xe có 'Mazda' trong sub_data_unique. Có bao nhiêu xe thỏa điều kiện này?
7. Trong sub_data_unique, cho biết giá trị mpg lớn nhất? Có những dòng dữ liệu nào có mpg = mpg lớn nhất, in kết quả.
8. Lọc các dữ liệu thỏa các điểu kiện sau: mpg >= 25 và cyl=4 và gear=4
9. Thực hiện việc thống kê theo cyl, từ đó cho biết số lượng từng nhóm, cyl, hp lớn nhất, mpg nhỏ nhất
10. Trong sub_data, cho biết xe nào có km_per_litre lớn nhất, nhỏ nhất?

#### Note: dùng df = cbind(names = rownames(df), df) hoặc rownames_to_column(df, var = "names"): chuyển cột index thành cột "names"

In [ ]:
library(tidyverse)

In [209]:
df = mtcars
head(df)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [210]:
summary(df)

      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb      
 Min.   :0.0000   Min.   :3.000  

In [215]:
dim(df)

[1] 32 11

In [212]:
sub_data = select(df, mpg, hp, wt, gear)
head(sub_data)

mpg  hp  wt    gear
Mazda RX4         21.0 110 2.620 4   
Mazda RX4 Wag     21.0 110 2.875 4   
Datsun 710        22.8  93 2.320 4   
Hornet 4 Drive    21.4 110 3.215 3   
Hornet Sportabout 18.7 175 3.440 3   
Valiant           18.1 105 3.460 3

In [213]:
sub_data$km_per_litre = sub_data$mpg * 0.425
head(sub_data)

mpg  hp  wt    gear km_per_litre
Mazda RX4         21.0 110 2.620 4    8.9250      
Mazda RX4 Wag     21.0 110 2.875 4    8.9250      
Datsun 710        22.8  93 2.320 4    9.6900      
Hornet 4 Drive    21.4 110 3.215 3    9.0950      
Hornet Sportabout 18.7 175 3.440 3    7.9475      
Valiant           18.1 105 3.460 3    7.6925

In [214]:
sub_data_unique = distinct(df)
head(sub_data_unique)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [216]:
dim(sub_data_unique)

[1] 32 11

In [218]:
sub_data_unique = arrange(sub_data_unique, desc(mpg), hp)
head(sub_data_unique)

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Fiat X1-9      27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2

In [231]:
filter(sub_data_unique, grepl('Mazda', rownames(sub_data_unique)))

mpg cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4     21  6   160  110 3.9  2.620 16.46 0  1  4    4   
Mazda RX4 Wag 21  6   160  110 3.9  2.875 17.02 0  1  4    4

In [232]:
max(sub_data_unique$mpg)

[1] 33.9

In [233]:
filter(sub_data_unique, sub_data_unique$mpg == max(sub_data_unique$mpg))

mpg  cyl disp hp drat wt    qsec vs am gear carb
Toyota Corolla 33.9 4   71.1 65 4.22 1.835 19.9 1  1  4    1

In [234]:
# mpg >= 25 và cyl=4 và gear=4
filter(sub_data_unique, sub_data_unique$mpg >= 25 & sub_data_unique$cyl==4 & sub_data_unique$gear==4)

mpg  cyl disp hp drat wt    qsec  vs am gear carb
Toyota Corolla 33.9 4   71.1 65 4.22 1.835 19.90 1  1  4    1   
Fiat 128       32.4 4   78.7 66 4.08 2.200 19.47 1  1  4    1   
Honda Civic    30.4 4   75.7 52 4.93 1.615 18.52 1  1  4    2   
Fiat X1-9      27.3 4   79.0 66 4.08 1.935 18.90 1  1  4    1

In [239]:
group = group_by(sub_data_unique, cyl)
summary = summarize(group,
                    max.hp = max(hp, na.rm=T),
                    min.mpg = min(mpg, na.rm=T))
summary

cyl max.hp min.mpg
1 4   113    21.4   
2 6   175    17.8   
3 8   335    10.4

In [242]:
filter(sub_data, sub_data$km_per_litre == min(sub_data$km_per_litre))

mpg  hp  wt    gear km_per_litre
Cadillac Fleetwood  10.4 205 5.250 3    4.42        
Lincoln Continental 10.4 215 5.424 3    4.42